[package]
name = "hexawaker"
version = "0.1.0"
edition = "2024"

[dependencies]
burn = "0.21.0"
burn-flex = "0.21.0"
burn-store = "0.21.0"
burn-vision = "0.21.0"
chrono = { version = "0.4", default-features = false, features = ["clock"] }
image = "0.25.10"
imageproc = "0.27.0"

[build-dependencies]
burn-onnx = "0.21.0"
